#! /usr/bin/env php
<?php
/**
 * Part of the Stripe package.
 *
 * NOTICE OF LICENSE
 *
 * Licensed under the Cartalyst PSL License.
 *
 * This source file is subject to the Cartalyst PSL License that is
 * bundled with this package in the license.txt file.
 *
 * @package    Stripe
 * @version    1.0.0
 * @author     Cartalyst LLC
 * @license    Cartalyst PSL
 * @copyright  (c) 2011-2014, Cartalyst LLC
 * @link       http://cartalyst.com
 */

if ( ! file_exists($path = __DIR__.'/vendor/autoload.php'))
{
	$path = __DIR__.'/../../autoload.php';
}

require $path;

$app = new Symfony\Component\Console\Application('Cartalyst Stripe CLI Tool', '0.2.0');

// $app->add(new Cartalyst\Stripe\Console\SyncCommand);
$app->add(new Cartalyst\Stripe\Console\SchemaCommand);

$app->run();
